/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.iftm.pv.cinema.cine3m.view.gerenciamento.cliente;

import br.com.iftm.pv.cinema.cine3m.controller.GerenciaCliente;
import br.com.iftm.pv.cinema.cine3m.model.Pessoa;
import br.com.iftm.pv.cinema.cine3m.model.Cliente;
import br.com.iftm.pv.cinema.cine3m.view.gerenciamento.util.ComboBoxUtils;
import javax.swing.JDesktopPane;

/**
 *
 * @author Felipe Soares
 */
public class AtualizaCliente extends javax.swing.JInternalFrame {

    CadastroCliente cadastroCliente;
    GerenciaCliente gerenciaCliente;
    JDesktopPane jdp;

    public AtualizaCliente(CadastroCliente cadastroCliente, GerenciaCliente gerenciaCliente, JDesktopPane jdp) {
        initComponents();
        this.cadastroCliente = cadastroCliente;
        this.gerenciaCliente = gerenciaCliente;
        this.jdp = jdp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        lbCliente2 = new javax.swing.JLabel();
        cbCliente2 = new javax.swing.JComboBox<>();
        btnAtualizarCliente = new javax.swing.JButton();

        setClosable(true);

        jPanel8.setBackground(java.awt.Color.darkGray);

        lbCliente2.setForeground(new java.awt.Color(255, 255, 255));
        lbCliente2.setText("Clientes:");

        cbCliente2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCliente2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbCliente2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbCliente2FocusGained(evt);
            }
        });

        btnAtualizarCliente.setText("Confirmar");
        btnAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbCliente2, 0, 286, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnAtualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCliente2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnAtualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCliente2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCliente2AncestorAdded
        ComboBoxUtils.carregarComboBox(cbCliente2, gerenciaCliente.relatorio());
    }//GEN-LAST:event_cbCliente2AncestorAdded

    private void btnAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarClienteActionPerformed
        Cliente clienteSelecionado = (Cliente) this.cbCliente2.getSelectedItem();
        this.cadastroCliente.getTfNomeCliente().setText(clienteSelecionado.getNome());
        this.cadastroCliente.getTfCpfCliente().setText(clienteSelecionado.getCpf());
        this.cadastroCliente.getLbTituloTelaCliente().setText("Atualização de Cliente");
        this.cadastroCliente.getBtnCadastrarCliente().setText("Atualizar");
        this.cadastroCliente.getBtnCadastrarCliente().setVisible(true);
        this.cadastroCliente.getTfNomeCliente().setEditable(true);
        this.cadastroCliente.getTfCpfCliente().setEditable(true);
        this.cadastroCliente.setClienteSelecionado(clienteSelecionado);
        this.jdp.add(cadastroCliente);
        this.cadastroCliente.setVisible(true);
    }//GEN-LAST:event_btnAtualizarClienteActionPerformed

    private void cbCliente2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbCliente2FocusGained
        cbCliente2AncestorAdded(null);
    }//GEN-LAST:event_cbCliente2FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarCliente;
    private javax.swing.JComboBox<Pessoa> cbCliente2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lbCliente2;
    // End of variables declaration//GEN-END:variables
}
