@startuml Cine3m

abstract class Pessoa{
    -nome: String
    -cpf: String
}

class Conta{
    -login: String
    -senha: String 
}

class Funcionario{
    -login: String 
    -senha: Senha
    -conta: Conta
}

class Cliente{

}

class Filme{
    -id: Integer 
    -genero: String
    -nome: String
    -descricao: String
    -atores: ArrayList<> 
    -diretor: String 
}

class Poltrona{
    -id: Integer 
    -livre: Boolean 
}

class Sala{
    -id: Integer 
    -qtdAssentos: 
    -numero: Integer 
    -poltronas: Poltrona[30]
}

class Sessao{
    -filme: Filme 
    -horario: LocalDateTime
    -sala: Sala 
}

class Ingresso{
    -filme: Filme
    -cliente: Cliente
    -tipo:  TipoINgresso
}

enum TipoIngresso{
    MEIA,
    INTEIRA
}

/' Funcionario
Cliente
Produto
Filmes
Sala
Ingresso
Sessão'/


@enduml