/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.iftm.pv.cinema.cine3m.view.gerenciamento.ingresso.auxiliares;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Felipe Soares
 */
public class ConfirmaCompra extends javax.swing.JInternalFrame {

    private Integer qtdMaxPoltronas;
    private SpinnerNumberModel spinnerModelInteira;
    private SpinnerNumberModel spinnerModelMeia;
    private Double valorTotal;
    private Double valorSessao;

    public ConfirmaCompra(int qtdMaxPoltronas, Double valorSessao) {
        this.qtdMaxPoltronas = qtdMaxPoltronas;
        this.spinnerModelInteira = new SpinnerNumberModel(0, 0, qtdMaxPoltronas, 1);
        this.spinnerModelMeia = new SpinnerNumberModel(0, 0, qtdMaxPoltronas, 1);
        this.valorSessao = valorSessao;
        initComponents();
        this.jsInteira.setModel(spinnerModelInteira);
        this.jsMeia.setModel(spinnerModelMeia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfValorTotal = new javax.swing.JTextField();
        lbValorTotal = new javax.swing.JLabel();
        jsInteira = new javax.swing.JSpinner();
        jsMeia = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        lbValorTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbValorTotal.setText("Valor Total :");

        jsInteira.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsInteiraStateChanged(evt);
            }
        });

        jsMeia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsMeiaStateChanged(evt);
            }
        });

        jLabel1.setText("Quantidade:");

        jLabel2.setText("Inteira");

        jLabel3.setText("Meia");

        jButton1.setText("CONFIRMAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfValorTotal)
                    .addComponent(jsInteira, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsMeia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsInteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsMeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addComponent(lbValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsInteiraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsInteiraStateChanged
        int qtdInteira = (int) jsInteira.getValue();
        spinnerModelMeia.setMaximum(qtdMaxPoltronas - qtdInteira);
        calcularValorTotal();
    }//GEN-LAST:event_jsInteiraStateChanged

    private void jsMeiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsMeiaStateChanged
        int qtdMeia = (int) jsMeia.getValue();
        spinnerModelInteira.setMaximum(qtdMaxPoltronas - qtdMeia);
        calcularValorTotal();
    }//GEN-LAST:event_jsMeiaStateChanged

    private void calcularValorTotal() {
        int qtdInteira = (int) jsInteira.getValue();
        int qtdMeia = (int) jsMeia.getValue();

        double valorIngressoInteira = qtdInteira * valorSessao;
        double valorIngressoMeia = qtdMeia * (valorSessao / 2.0);

        valorTotal = valorIngressoInteira + valorIngressoMeia;
        tfValorTotal.setText(String.valueOf(valorTotal));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jsInteira;
    private javax.swing.JSpinner jsMeia;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JTextField tfValorTotal;
    // End of variables declaration//GEN-END:variables
}
