/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.iftm.pv.cinema.cine3m.view.gerenciamento.sessao;

import br.com.iftm.pv.cinema.cine3m.controller.GerenciaFilme;
import br.com.iftm.pv.cinema.cine3m.controller.GerenciaSala;
import br.com.iftm.pv.cinema.cine3m.controller.GerenciaSessao;
import br.com.iftm.pv.cinema.cine3m.model.Filme;
import br.com.iftm.pv.cinema.cine3m.model.Sala;
import br.com.iftm.pv.cinema.cine3m.model.Sessao;
import br.com.iftm.pv.cinema.cine3m.view.util.ComboBoxUtils;
import br.com.iftm.pv.cinema.cine3m.view.util.ValidaCampo;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Soares
 */
public class CadastroSessao extends javax.swing.JInternalFrame {

    private final GerenciaSessao gerenciaSessao;
    private final GerenciaSala gerenciaSala;
    private final GerenciaFilme gerenciaFilme;
    private Sessao sessaoSelecionada;

    public CadastroSessao(GerenciaSessao gerenciaSessao, GerenciaSala gerenciaSala, GerenciaFilme gerenciaFilme) {
        initComponents();
        this.gerenciaFilme = gerenciaFilme;
        this.gerenciaSala = gerenciaSala;
        this.gerenciaSessao = gerenciaSessao;
        this.btnCadastrarSessao.setEnabled(false);
    }

    public JButton getBtnCadastrarSessao() {
        return btnCadastrarSessao;
    }

    public void setBtnCadastrarSessao(JButton btnCadastrarSessao) {
        this.btnCadastrarSessao = btnCadastrarSessao;
    }

    public JComboBox<Filme> getCbFilmesSessao() {
        return cbFilmesSessao;
    }

    public void setCbFilmesSessao(JComboBox<Filme> cbFilmesSessao) {
        this.cbFilmesSessao = cbFilmesSessao;
    }

    public JComboBox<Sala> getCbSalasSessao() {
        return cbSalasSessao;
    }

    public void setCbSalasSessao(JComboBox<Sala> cbSalasSessao) {
        this.cbSalasSessao = cbSalasSessao;
    }

    public JLabel getLbDataHora() {
        return lbData;
    }

    public void setLbDataHora(JLabel lbDataHora) {
        this.lbData = lbDataHora;
    }

    public JLabel getLbDataHora1() {
        return lbHora;
    }

    public void setLbDataHora1(JLabel lbDataHora1) {
        this.lbHora = lbDataHora1;
    }

    public JLabel getLbFilmes() {
        return lbFilmes;
    }

    public void setLbFilmes(JLabel lbFilmes) {
        this.lbFilmes = lbFilmes;
    }

    public JLabel getLbSalas() {
        return lbSalas;
    }

    public void setLbSalas(JLabel lbSalas) {
        this.lbSalas = lbSalas;
    }

    public JLabel getLbTituloTelaSessao() {
        return lbTituloTelaSessao;
    }

    public void setLbTituloTelaSessao(JLabel lbTituloTelaSessao) {
        this.lbTituloTelaSessao = lbTituloTelaSessao;
    }

    public Sessao getSessaoSelecionada() {
        return sessaoSelecionada;
    }

    public void setSessaoSelecionada(Sessao sessaoSelecionada) {
        this.sessaoSelecionada = sessaoSelecionada;
    }

    public JLabel getLbValor() {
        return lbValor;
    }

    public void setLbValor(JLabel lbValor) {
        this.lbValor = lbValor;
    }

    public JFormattedTextField getTfDataSessao() {
        return tfDataSessao;
    }

    public void setTfDataSessao(JFormattedTextField tfDataSessao) {
        this.tfDataSessao = tfDataSessao;
    }

    public JFormattedTextField getTfHorarioSessao() {
        return tfHorarioSessao;
    }

    public void setTfHorarioSessao(JFormattedTextField tfHorarioSessao) {
        this.tfHorarioSessao = tfHorarioSessao;
    }

    public JFormattedTextField getTfValorSessao() {
        return tfValorSessao;
    }

    public void setTfValorSessao(JFormattedTextField tfValorSessao) {
        this.tfValorSessao = tfValorSessao;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloTelaSessao = new javax.swing.JLabel();
        lbFilmes = new javax.swing.JLabel();
        cbFilmesSessao = new javax.swing.JComboBox<>();
        cbSalasSessao = new javax.swing.JComboBox<>();
        lbSalas = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        btnCadastrarSessao = new javax.swing.JButton();
        lbHora = new javax.swing.JLabel();
        tfHorarioSessao = new javax.swing.JFormattedTextField();
        tfDataSessao = new javax.swing.JFormattedTextField();
        tfValorSessao = new javax.swing.JFormattedTextField();

        setClosable(true);

        lbTituloTelaSessao.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lbTituloTelaSessao.setText("Cadastro de Sessão");

        lbFilmes.setForeground(new java.awt.Color(255, 255, 255));
        lbFilmes.setText("FIlmes");

        cbFilmesSessao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFilmesSessaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbSalasSessao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbSalasSessaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lbSalas.setForeground(new java.awt.Color(255, 255, 255));
        lbSalas.setText("Salas");

        lbValor.setForeground(new java.awt.Color(255, 255, 255));
        lbValor.setText("Valor");

        lbData.setForeground(new java.awt.Color(255, 255, 255));
        lbData.setText("Data:");

        btnCadastrarSessao.setText("Cadastrar");
        btnCadastrarSessao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnCadastrarSessaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnCadastrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarSessaoActionPerformed(evt);
            }
        });

        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setText("Hora");

        try {
            tfHorarioSessao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfDataSessao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfValorSessao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDataSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfValorSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFilmesSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSalasSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHorarioSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addComponent(lbTituloTelaSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btnCadastrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTituloTelaSessao)
                .addGap(33, 33, 33)
                .addComponent(lbFilmes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFilmesSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSalas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSalasSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbData)
                .addGap(7, 7, 7)
                .addComponent(tfDataSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHorarioSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFilmesSessaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFilmesSessaoAncestorAdded
        ComboBoxUtils.carregarComboBox(cbFilmesSessao, gerenciaFilme.relatorio());
        if (this.sessaoSelecionada != null) {
            cbFilmesSessao.setSelectedItem(sessaoSelecionada.getFilme());
        }
    }//GEN-LAST:event_cbFilmesSessaoAncestorAdded

    private void cbSalasSessaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbSalasSessaoAncestorAdded
        ComboBoxUtils.carregarComboBox(cbSalasSessao, gerenciaSala.relatorio());
        if (this.sessaoSelecionada != null) {
            cbSalasSessao.setSelectedItem(sessaoSelecionada.getSala());
        }
    }//GEN-LAST:event_cbSalasSessaoAncestorAdded

    private void btnCadastrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarSessaoActionPerformed
        Filme filmeSelecionado = (Filme) cbFilmesSessao.getSelectedItem();
        Sala salaSelecionada = (Sala) cbSalasSessao.getSelectedItem();

        String dataSessao = tfDataSessao.getText();
        String horaSessao = tfHorarioSessao.getText();
        String valorSessao = tfValorSessao.getText();

        if (ValidaCampo.validar(dataSessao.replaceAll("[/]", "").trim(), lbData, this)
                && ValidaCampo.validar(horaSessao.replaceAll("[:]", "").trim(), lbHora, this)
                && ValidaCampo.validar(valorSessao, lbValor, this)) {

            LocalDate data;
            LocalTime hora;

            try {
                data = LocalDate.parse(dataSessao, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            } catch (DateTimeException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                hora = LocalTime.parse(horaSessao, DateTimeFormatter.ofPattern("HH:mm:ss"));
            } catch (DateTimeException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Double valor = Double.valueOf(tfValorSessao.getText());

            Sessao sessao = new Sessao(filmeSelecionado, data, hora, salaSelecionada, valor);

            if (btnCadastrarSessao.getText().equals("Cadastrar")) {
                Boolean sucesso = gerenciaSessao.cadastrar(sessao);
                JOptionPane.showMessageDialog(this, sucesso ? "Sessão cadstrada com sucesso " : "Sessão já Cadastrada!",
                        "Cadastro Cliente", sucesso ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Sessão atualizada com sucesso!", "Atualizar", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                getDesktopPane().remove(this);
            }
            tfValorSessao.setText("");
            tfDataSessao.setText("");
            tfHorarioSessao.setText("");
        }
    }//GEN-LAST:event_btnCadastrarSessaoActionPerformed

    private void btnCadastrarSessaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnCadastrarSessaoAncestorAdded
        if (cbFilmesSessao.getModel().getSize() > 0
                && cbSalasSessao.getModel().getSize() > 0) {
            btnCadastrarSessao.setEnabled(true);
        }
    }//GEN-LAST:event_btnCadastrarSessaoAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarSessao;
    private javax.swing.JComboBox<Filme> cbFilmesSessao;
    private javax.swing.JComboBox<Sala> cbSalasSessao;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbFilmes;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbSalas;
    private javax.swing.JLabel lbTituloTelaSessao;
    private javax.swing.JLabel lbValor;
    private javax.swing.JFormattedTextField tfDataSessao;
    private javax.swing.JFormattedTextField tfHorarioSessao;
    private javax.swing.JFormattedTextField tfValorSessao;
    // End of variables declaration//GEN-END:variables
}
