/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.iftm.pv.cinema.cine3m.view.gerenciamento.sessao;

import br.com.iftm.pv.cinema.cine3m.controller.GerenciaSessao;
import br.com.iftm.pv.cinema.cine3m.model.Sessao;
import br.com.iftm.pv.cinema.cine3m.view.util.ListUtils;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author Felipe Soares
 */
public class ConsultaSessao extends javax.swing.JInternalFrame {

    private CadastroSessao cadastroSessao;
    private GerenciaSessao gerenciaSessao;
    private List<Sessao> sessoes;

    public ConsultaSessao(CadastroSessao cadastroSessao, GerenciaSessao gerenciaSessao) {
        initComponents();
        this.cadastroSessao = cadastroSessao;
        this.gerenciaSessao = gerenciaSessao;
        this.btnConfirmar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        lbTituloTelaCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSessao = new javax.swing.JList<>();

        setClosable(true);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lbTituloTelaCliente.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lbTituloTelaCliente.setText("Consulta Sessões");

        listSessao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSessao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listSessaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listSessao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listSessaoFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(listSessao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTituloTelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTituloTelaCliente)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        Sessao sessaoSelecionada = (Sessao) this.listSessao.getSelectedValue();
        this.cadastroSessao.getBtnCadastrarSessao().setVisible(false);
        this.cadastroSessao.getCbFilmesSessao().setSelectedItem(sessaoSelecionada.getFilme());
        this.cadastroSessao.getCbSalasSessao().setSelectedItem(sessaoSelecionada.getSala());
        this.cadastroSessao.getTfDataSessao().setText(sessaoSelecionada.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        this.cadastroSessao.getTfHorarioSessao().setText(sessaoSelecionada.getHora().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        this.cadastroSessao.getTfValorSessao().setText(String.valueOf(sessaoSelecionada.getValor()));
        this.cadastroSessao.getCbFilmesSessao().setEnabled(false);
        this.cadastroSessao.getCbSalasSessao().setEnabled(false);
        this.cadastroSessao.getTfValorSessao().setEditable(false);
        this.cadastroSessao.getTfDataSessao().setEditable(false);
        this.cadastroSessao.getTfHorarioSessao().setEditable(false);
        this.cadastroSessao.getLbTituloTelaSessao().setText("Consulta de Sessões");
        
        getDesktopPane().add(cadastroSessao);
        this.cadastroSessao.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void listSessaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listSessaoAncestorAdded
        sessoes = gerenciaSessao.relatorio();
        ListUtils.carregarList(listSessao, sessoes);
        if (!sessoes.isEmpty()) {
            btnConfirmar.setEnabled(true);
            listSessao.setSelectedIndex(0);
        } else {
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_listSessaoAncestorAdded

    private void listSessaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listSessaoFocusGained
        listSessaoAncestorAdded(null);
    }//GEN-LAST:event_listSessaoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTituloTelaCliente;
    private javax.swing.JList<Sessao> listSessao;
    // End of variables declaration//GEN-END:variables
}
