package br.com.iftm.pv.cinema.sistemacinema;
import br.com.iftm.pv.cinema.sistemacinema.gerenciamento.GerenciaCliente;
import br.com.iftm.pv.cinema.sistemacinema.gerenciamento.GerenciaFilme;
import br.com.iftm.pv.cinema.sistemacinema.gerenciamento.GerenciaFuncionario;
import br.com.iftm.pv.cinema.sistemacinema.gerenciamento.GerenciaIngresso;
import br.com.iftm.pv.cinema.sistemacinema.gerenciamento.GerenciaSala;
import br.com.iftm.pv.cinema.sistemacinema.gerenciamento.GerenciaSessao;
import br.com.iftm.pv.cinema.sistemacinema.model.Cliente;
import br.com.iftm.pv.cinema.sistemacinema.model.Filme;
import br.com.iftm.pv.cinema.sistemacinema.model.Funcionario;
import br.com.iftm.pv.cinema.sistemacinema.model.Ingresso;
import br.com.iftm.pv.cinema.sistemacinema.model.Sala;
import br.com.iftm.pv.cinema.sistemacinema.model.Sessao;
import java.util.ArrayList;
import java.util.List;

public class Cine3m extends javax.swing.JFrame {

    List<Filme> filmes = new ArrayList<Filme>();
    List<Funcionario> funcionarios = new ArrayList<Funcionario>();
    List<Sessao> sessoes = new ArrayList<Sessao>();
    List<Ingresso> ingressos = new ArrayList<Ingresso>();
    List<Sala> salas = new ArrayList<Sala>();
    List<Cliente> clientes = new ArrayList<Cliente>();

    GerenciaCliente gerenciaCliente = new GerenciaCliente(clientes);
    GerenciaFilme gerenciaFilme = new GerenciaFilme(filmes);
    GerenciaFuncionario gerenciaFuncionario = new GerenciaFuncionario(funcionarios);
    GerenciaSessao gerenciaSessao = new GerenciaSessao(sessoes);
    GerenciaIngresso gerenciaIngresso = new GerenciaIngresso(ingressos);
    GerenciaSala gerenciaSala = new GerenciaSala(salas);

    public Cine3m() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cine3m().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
