package br.com.iftm.pv.cinema.cine3m.enums;

public enum EnumValidacoes {
    FUNCIONARIO_CPF_JA_CADASTRADO,
    FUNCIONARIO_CPF_INVALIDO,
    FUNCIONARIO_LOGIN_JA_CADASTRADO,
    FUNCIONARIO_SUCESSO,

    CLIENTE_CPF_JA_CADASTRADO,
    CLIENTE_CPF_INVALIDO,
    CLIENTE_SUCESSO,
    
    VENDA_SUCESSO,
    VENDA_PROMOCAO,
    VENDA_CANCELADA,
}
