package br.com.iftm.pv.cinema.cine3m.enums;

public enum EnumValidacoes {
    FUNCIONARIO_CPF_JA_CADASTRADO,
    FUNCIONARIO_CPF_INVALIDO,
    FUNCIONARIO_LOGIN_JA_CADASTRADO,
    FUNCIONARIO_SUCESSO,

    CLIENTE_CPF_JA_CADASTRADO,
    CLIENTE_CPF_INVALIDO,
    CLIENTE_SUCESSO,
    
    SESSAO_JA_CADASTRADA,
    SESSAO_HORARIO_JA_UTILIZADO,
    SESSAO_SUCESSO,
    
    FILME_JA_CADASTRADO,
    FILME_SUCESSO,
    
    SALA_JA_CADASTRADA,
    SALA_SUCESSO,
    
    VENDA_SUCESSO,
    VENDA_JA_CANCELADA,
    VENDA_CANCELADA,
    VENDA_PROMOCAO,
    
      RESERVA_SUCESSO,
}
