package br.com.iftm.pv.cinema.cine3m;
import br.com.iftm.pv.cinema.cine3m.gerenciamento.GerenciaCliente;
import br.com.iftm.pv.cinema.cine3m.gerenciamento.GerenciaFilme;
import br.com.iftm.pv.cinema.cine3m.gerenciamento.GerenciaFuncionario;
import br.com.iftm.pv.cinema.cine3m.gerenciamento.GerenciaIngresso;
import br.com.iftm.pv.cinema.cine3m.gerenciamento.GerenciaSala;
import br.com.iftm.pv.cinema.cine3m.gerenciamento.GerenciaSessao;
import br.com.iftm.pv.cinema.cine3m.model.Cliente;
import br.com.iftm.pv.cinema.cine3m.model.Filme;
import br.com.iftm.pv.cinema.cine3m.model.Funcionario;
import br.com.iftm.pv.cinema.cine3m.model.Ingresso;
import br.com.iftm.pv.cinema.cine3m.model.Sala;
import br.com.iftm.pv.cinema.cine3m.model.Sessao;
import java.util.ArrayList;
import java.util.List;

public class Cine3m extends javax.swing.JFrame {

    List<Filme> filmes = new ArrayList<Filme>();
    List<Funcionario> funcionarios = new ArrayList<Funcionario>();
    List<Sessao> sessoes = new ArrayList<Sessao>();
    List<Ingresso> ingressos = new ArrayList<Ingresso>();
    List<Sala> salas = new ArrayList<Sala>();
    List<Cliente> clientes = new ArrayList<Cliente>();

    GerenciaCliente gerenciaCliente = new GerenciaCliente(clientes);
    GerenciaFilme gerenciaFilme = new GerenciaFilme(filmes);
    GerenciaFuncionario gerenciaFuncionario = new GerenciaFuncionario(funcionarios);
    GerenciaSessao gerenciaSessao = new GerenciaSessao(sessoes);
    GerenciaIngresso gerenciaIngresso = new GerenciaIngresso(ingressos);
    GerenciaSala gerenciaSala = new GerenciaSala(salas);

    public Cine3m() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_email = new javax.swing.JLabel();
        lb_senha = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_senha = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_email.setText("Usuario");

        lb_senha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_senha.setText("Senha");

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        btn_login.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_login.setText("Login");

        btn_cadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_cadastrar.setText("Cadastre-se");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_email)
                            .addComponent(lb_senha)
                            .addComponent(tf_email)
                            .addComponent(tf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(btn_login))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(btn_cadastrar)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(lb_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_login)
                .addGap(41, 41, 41)
                .addComponent(btn_cadastrar)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cine3m.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cine3m().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_senha;
    // End of variables declaration//GEN-END:variables
}
